/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    /* Local Variables */
    
entry:
    bunzo_print_string("Hello, Bunzo!");
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    bunzo_gc_init(&argc);
    __main__();
    bunzo_gc_cleanup();
    return 0;
}
