/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
int64_t var_i;
int64_t var_sum;

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    bool _r1;
    int64_t _r2;
    int64_t _r3;
    int64_t _r4;
    int64_t _r5;
    int64_t _r6;
    /* Local Variables */
    
entry:
    var_sum = 0LL;
    var_i = 0LL;
    goto loop_header_0;
loop_header_0:
    _r0 = var_i;
    _r1 = _r0 < 1000000LL;
    if (_r1) goto loop_body_1; else goto loop_exit_2;
loop_body_1:
    _r2 = var_sum;
    _r3 = _r2 + 1LL;
    var_sum = _r3;
    _r4 = var_i;
    _r5 = _r4 + 1LL;
    var_i = _r5;
    goto loop_header_0;
loop_exit_2:
    _r6 = var_sum;
    bunzo_print_int(_r6);
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
