/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
int64_t var_res;

/* Forward Declarations */
void __main__(void);
int64_t recurse(int64_t n);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    int64_t _r1;
    /* Local Variables */
    
entry:
    _r0 = recurse(1000LL);
    var_res = _r0;
    _r1 = var_res;
    bunzo_print_int(_r1);
    return;
}

int64_t recurse(int64_t n) {
    /* Virtual Registers */
    int64_t _r0;
    bool _r1;
    int64_t _r2;
    int64_t _r3;
    int64_t _r4;
    int64_t _r5;
    /* Local Variables */
    
entry:
    _r0 = n;
    _r1 = _r0 <= 0LL;
    if (_r1) goto then_0; else goto merge_2;
then_0:
    return 0LL;
merge_2:
    _r2 = n;
    _r3 = _r2 - 1LL;
    _r4 = recurse(_r3);
    _r5 = 1LL + _r4;
    return _r5;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
