use crate::ast::node::{
    Expression, Program, Statement,
};
use std::collections::HashMap;

/// Represents a diagnostic warning generated by the linter.
#[derive(Debug, Clone, PartialEq)]
pub struct LintWarning {
    /// Lint rule code, e.g. "LN0001".
    pub code: String,
    /// Human-readable message explaining the style or quality issue.
    pub message: String,
    /// 1-based line number.
    pub line: usize,
    /// 1-based column number.
    pub column: usize,
}

struct VarDecl {
    line: usize,
    column: usize,
    used: bool,
}

/// The Bunzo Linter state and engine.
pub struct Linter {
    warnings: Vec<LintWarning>,
    scopes: Vec<HashMap<String, VarDecl>>,
}

impl Linter {
    /// Creates a new linter instance.
    pub fn new() -> Self {
        Linter {
            warnings: Vec::new(),
            scopes: vec![HashMap::new()], // Initialize with global scope
        }
    }

    /// Lints a parsed Bunzo program and returns a list of warnings.
    pub fn lint(mut self, program: &Program) -> Vec<LintWarning> {
        self.check_statements(&program.statements);
        
        // Pop the global scope and collect unused warnings
        self.pop_scope();
        
        // Sort warnings by line and column
        self.warnings.sort_by(|a, b| {
            a.line.cmp(&b.line).then_with(|| a.column.cmp(&b.column))
        });
        
        self.warnings
    }

    fn push_scope(&mut self) {
        self.scopes.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        if let Some(scope) = self.scopes.pop() {
            for (name, decl) in scope {
                if !decl.used {
                    self.warnings.push(LintWarning {
                        code: "LQ0002".to_string(),
                        message: format!("Unused local variable '{}'", name),
                        line: decl.line,
                        column: decl.column,
                    });
                }
            }
        }
    }

    fn declare_var(&mut self, name: &str, line: usize, column: usize) {
        if let Some(scope) = self.scopes.last_mut() {
            scope.insert(
                name.to_string(),
                VarDecl {
                    line,
                    column,
                    used: false,
                },
            );
        }
    }

    fn reference_var(&mut self, name: &str) {
        for scope in self.scopes.iter_mut().rev() {
            if let Some(decl) = scope.get_mut(name) {
                decl.used = true;
                break;
            }
        }
    }

    fn check_statements(&mut self, statements: &[Statement]) {
        for stmt in statements {
            self.check_statement(stmt);
        }
    }

    fn check_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::LetDeclaration {
                name,
                initializer,
                line,
                column,
            } => {
                self.check_variable_style(name, false, *line, *column);
                self.declare_var(name, *line, *column);
                
                if let Expression::BooleanLiteral { .. } = initializer {
                    if !is_boolean_prefix(name) {
                        self.warnings.push(LintWarning {
                            code: "LN0005".to_string(),
                            message: format!(
                                "Boolean variable '{}' should start with is_, has_, can_, or should_",
                                name
                            ),
                            line: *line,
                            column: *column,
                        });
                    }
                }
                
                self.check_expression(initializer, true);
            }

            Statement::ConstDeclaration {
                name,
                initializer,
                line,
                column,
            } => {
                self.check_variable_style(name, true, *line, *column);
                self.declare_var(name, *line, *column);
                
                if let Expression::BooleanLiteral { .. } = initializer {
                    if !is_boolean_prefix(name) {
                        self.warnings.push(LintWarning {
                            code: "LN0005".to_string(),
                            message: format!(
                                "Boolean constant '{}' should start with is_, has_, can_, or should_",
                                name
                            ),
                            line: *line,
                            column: *column,
                        });
                    }
                }

                self.check_expression(initializer, true);
            }

            Statement::PrintStatement { argument, .. } => {
                self.check_expression(argument, false);
            }

            Statement::ExpressionStatement { expression } => {
                self.check_expression(expression, false);
            }

            Statement::FunctionDeclaration {
                name,
                params,
                body,
                is_abstract,
                line,
                column,
                ..
            } => {
                self.check_function_style(name, *line, *column);
                
                if body.is_empty() && !*is_abstract {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: format!("Empty body in non-abstract function '{}'", name),
                        line: *line,
                        column: *column,
                    });
                }

                self.push_scope();
                for param in params {
                    self.check_variable_style(&param.name, false, param.line, param.column);
                    self.declare_var(&param.name, param.line, param.column);
                    self.reference_var(&param.name); // Ignore unused param warnings in linter for simplicity
                }
                self.check_statements(body);
                self.pop_scope();
            }

            Statement::ReturnStatement { value, .. } => {
                if let Some(val) = value {
                    self.check_expression(val, false);
                }
            }

            Statement::Assignment { name, value, .. } => {
                self.reference_var(name);
                self.check_expression(value, false);
            }

            Statement::IfStatement {
                condition,
                then_branch,
                else_branch,
                line,
                column,
            } => {
                self.check_expression(condition, false);
                
                if then_branch.is_empty() {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: "Empty 'then' branch in if statement".to_string(),
                        line: *line,
                        column: *column,
                    });
                }
                
                self.push_scope();
                self.check_statements(then_branch);
                self.pop_scope();

                if let Some(else_stmt) = else_branch {
                    if else_stmt.is_empty() {
                        self.warnings.push(LintWarning {
                            code: "LQ0001".to_string(),
                            message: "Empty 'else' branch in if statement".to_string(),
                            line: *line,
                            column: *column,
                        });
                    }
                    self.push_scope();
                    self.check_statements(else_stmt);
                    self.pop_scope();
                }
            }

            Statement::WhileStatement {
                condition,
                body,
                line,
                column,
            } => {
                self.check_expression(condition, false);
                
                if body.is_empty() {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: "Empty body in while loop".to_string(),
                        line: *line,
                        column: *column,
                    });
                }

                self.push_scope();
                self.check_statements(body);
                self.pop_scope();
            }

            Statement::ForStatement {
                variable,
                start,
                end,
                body,
                line,
                column,
            } => {
                self.check_expression(start, false);
                self.check_expression(end, false);
                
                if body.is_empty() {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: "Empty body in for loop".to_string(),
                        line: *line,
                        column: *column,
                    });
                }

                self.push_scope();
                self.check_variable_style(variable, false, *line, *column);
                self.declare_var(variable, *line, *column);
                self.check_statements(body);
                self.pop_scope();
            }

            Statement::StructDeclaration {
                name,
                fields,
                line,
                column,
            } => {
                self.check_type_style(name, *line, *column);
                for field in fields {
                    self.check_variable_style(&field.name, false, field.line, field.column);
                }
            }

            Statement::ClassDeclaration {
                name,
                fields,
                methods,
                line,
                column,
                ..
            } => {
                self.check_type_style(name, *line, *column);
                for field in fields {
                    self.check_variable_style(&field.name, false, field.line, field.column);
                }
                for method in methods {
                    self.check_statement(method);
                }
            }

            Statement::FieldAssignment {
                object,
                value,
                ..
            } => {
                self.check_expression(object, false);
                self.check_expression(value, false);
            }

            Statement::TryCatch {
                try_block,
                catch_var,
                catch_block,
                line,
                column,
            } => {
                if try_block.is_empty() {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: "Empty 'try' block".to_string(),
                        line: *line,
                        column: *column,
                    });
                }
                self.push_scope();
                self.check_statements(try_block);
                self.pop_scope();

                if catch_block.is_empty() {
                    self.warnings.push(LintWarning {
                        code: "LQ0001".to_string(),
                        message: "Empty 'catch' block".to_string(),
                        line: *line,
                        column: *column,
                    });
                }
                self.push_scope();
                self.check_variable_style(catch_var, false, *line, *column);
                self.declare_var(catch_var, *line, *column);
                self.check_statements(catch_block);
                self.pop_scope();
            }

            Statement::Throw { value, .. } => {
                self.check_expression(value, false);
            }

            Statement::ImportDeclaration { .. } => {}

            Statement::ExportDeclaration { declaration, .. } => {
                if let Some(decl) = declaration {
                    self.check_statement(decl);
                }
            }

            Statement::EnumDeclaration { name, line, column, .. } => {
                self.check_type_style(name, *line, *column);
            }

            Statement::MatchStatement { subject, arms, .. } => {
                self.check_expression(subject, false);
                for arm in arms {
                    self.push_scope();
                    self.check_statements(&arm.body);
                    self.pop_scope();
                }
            }

            Statement::InterfaceDeclaration { name, methods, line, column } => {
                self.check_type_style(name, *line, *column);
                for sig in methods {
                    self.check_function_style(&sig.name, sig.line, sig.column);
                    for param in &sig.params {
                        self.check_variable_style(&param.name, false, param.line, param.column);
                    }
                }
            }

            Statement::SpawnStatement { expression, .. } => {
                self.check_expression(expression, false);
            }

            _ => {}
        }
    }

    fn check_expression(&mut self, expr: &Expression, in_direct_decl: bool) {
        match expr {
            Expression::IntegerLiteral { value, line, column } => {
                if !in_direct_decl && *value != 0 && *value != 1 && *value != -1 {
                    self.warnings.push(LintWarning {
                        code: "LQ0003".to_string(),
                        message: format!("Magic number: '{}'", value),
                        line: *line,
                        column: *column,
                    });
                }
            }

            Expression::FloatLiteral { value, line, column } => {
                if !in_direct_decl && *value != 0.0 && *value != 1.0 && *value != -1.0 {
                    self.warnings.push(LintWarning {
                        code: "LQ0003".to_string(),
                        message: format!("Magic number: '{}'", value),
                        line: *line,
                        column: *column,
                    });
                }
            }

            Expression::Identifier { name, .. } => {
                self.reference_var(name);
            }

            Expression::BinaryOp { left, right, .. } => {
                self.check_expression(left, false);
                self.check_expression(right, false);
            }

            Expression::UnaryOp { operand, .. } => {
                self.check_expression(operand, false);
            }

            Expression::Grouping { expression, .. } => {
                self.check_expression(expression, false);
            }

            Expression::Call { callee, arguments, .. } => {
                self.check_expression(callee, false);
                for arg in arguments {
                    self.check_expression(arg, false);
                }
            }

            Expression::StructLiteral { fields, .. } => {
                for (_, value) in fields {
                    self.check_expression(value, false);
                }
            }

            Expression::FieldAccess { object, .. } => {
                self.check_expression(object, false);
            }

            Expression::ArrayLiteral { elements, .. } => {
                for elem in elements {
                    self.check_expression(elem, false);
                }
            }

            Expression::IndexExpression { object, index, .. } => {
                self.check_expression(object, false);
                self.check_expression(index, false);
            }

            Expression::EnumVariantExpr { payload, .. } => {
                if let Some(payload_expr) = payload {
                    self.check_expression(payload_expr, false);
                }
            }

            Expression::PropagateError { expression, .. } => {
                self.check_expression(expression, false);
            }

            Expression::AwaitExpr { expression, .. } => {
                self.check_expression(expression, false);
            }

            _ => {}
        }
    }

    fn check_variable_style(&mut self, name: &str, is_constant: bool, line: usize, column: usize) {
        if is_constant {
            if !is_upper_snake_case(name) {
                self.warnings.push(LintWarning {
                    code: "LN0004".to_string(),
                    message: format!("Constant '{}' should be in UPPER_SNAKE_CASE", name),
                    line,
                    column,
                });
            }
        } else {
            if !is_snake_case(name) {
                self.warnings.push(LintWarning {
                    code: "LN0001".to_string(),
                    message: format!("Variable '{}' should be in snake_case", name),
                    line,
                    column,
                });
            }
        }
    }

    fn check_function_style(&mut self, name: &str, line: usize, column: usize) {
        if !is_snake_case(name) {
            self.warnings.push(LintWarning {
                code: "LN0002".to_string(),
                message: format!("Function '{}' should be in snake_case", name),
                line,
                column,
            });
        }
    }

    fn check_type_style(&mut self, name: &str, line: usize, column: usize) {
        if !is_pascal_case(name) {
            self.warnings.push(LintWarning {
                code: "LN0003".to_string(),
                message: format!("Type '{}' should be in PascalCase", name),
                line,
                column,
            });
        }
    }
}

fn is_snake_case(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    s.chars().all(|c| c.is_lowercase() || c.is_numeric() || c == '_')
}

fn is_pascal_case(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    s.chars().next().unwrap().is_uppercase() && !s.contains('_') && s.chars().all(|c| c.is_alphanumeric())
}

fn is_upper_snake_case(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    s.chars().all(|c| c.is_uppercase() || c.is_numeric() || c == '_')
}

fn is_boolean_prefix(s: &str) -> bool {
    s.starts_with("is_") || s.starts_with("has_") || s.starts_with("can_") || s.starts_with("should_")
}
