/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */

/* Forward Declarations */
void __main__(void);
int64_t fib(int64_t n);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    /* Local Variables */
    
entry:
    _r0 = fib(7LL);
    bunzo_print_int(_r0);
    return;
}

int64_t fib(int64_t n) {
    /* Virtual Registers */
    int64_t _r0;
    bool _r1;
    int64_t _r2;
    int64_t _r3;
    int64_t _r4;
    int64_t _r5;
    int64_t _r6;
    int64_t _r7;
    int64_t _r8;
    int64_t _r9;
    /* Local Variables */
    
entry:
    _r0 = n;
    _r1 = _r0 <= 1LL;
    if (_r1) goto then_0; else goto merge_2;
then_0:
    _r2 = n;
    return _r2;
merge_2:
    _r3 = n;
    _r4 = _r3 - 1LL;
    _r5 = fib(_r4);
    _r6 = n;
    _r7 = _r6 - 2LL;
    _r8 = fib(_r7);
    _r9 = _r5 + _r8;
    return _r9;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
