/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
const char* var_a;
const char* var_b;
const char* var_c;

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    const char* _r0;
    const char* _r1;
    const char* _r2;
    const char* _r3;
    const char* _r4;
    bool _r5;
    const char* _r6;
    bool _r7;
    /* Local Variables */
    
entry:
    var_a = "hello ";
    var_b = "world";
    _r0 = var_a;
    _r1 = var_b;
    _r2 = bunzo_concat_strings(_r0, _r1);
    var_c = _r2;
    _r3 = var_c;
    bunzo_print_string(_r3);
    _r4 = var_c;
    _r5 = bunzo_equal_strings(_r4, "hello world");
    bunzo_print_bool(_r5);
    _r6 = var_c;
    _r7 = bunzo_notequal_strings(_r6, "hello world");
    bunzo_print_bool(_r7);
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
