/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
int64_t var_count;

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    bool _r1;
    int64_t _r2;
    int64_t _r3;
    int64_t _r4;
    /* Local Variables */
    
entry:
    var_count = 0LL;
    goto loop_header_0;
loop_header_0:
    _r0 = var_count;
    _r1 = _r0 < 3LL;
    if (_r1) goto loop_body_1; else goto loop_exit_2;
loop_body_1:
    _r2 = var_count;
    bunzo_print_int(_r2);
    _r3 = var_count;
    _r4 = _r3 + 1LL;
    var_count = _r4;
    goto loop_header_0;
loop_exit_2:
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
