/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
int64_t var_x;

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    bool _r1;
    /* Local Variables */
    
entry:
    var_x = 42LL;
    _r0 = var_x;
    _r1 = _r0 > 40LL;
    if (_r1) goto then_0; else goto else_1;
then_0:
    bunzo_print_string("greater");
    goto merge_2;
else_1:
    bunzo_print_string("less");
    goto merge_2;
merge_2:
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
