/* Generated by Bunzo Compiler (bzc) */
#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* Global Variables */
int64_t var_x;
int64_t var_y;

/* Forward Declarations */
void __main__(void);

void __main__(void) {
    /* Virtual Registers */
    int64_t _r0;
    int64_t _r1;
    int64_t _r2;
    int64_t _r3;
    int64_t _r4;
    int64_t _r5;
    int64_t _r6;
    int64_t _r7;
    int64_t _r8;
    int64_t _r9;
    int64_t _r10;
    int64_t _r11;
    /* Local Variables */
    
entry:
    var_x = 10LL;
    var_y = 20LL;
    _r0 = var_x;
    _r1 = var_y;
    _r2 = _r0 + _r1;
    bunzo_print_int(_r2);
    _r3 = var_y;
    _r4 = var_x;
    _r5 = _r3 - _r4;
    bunzo_print_int(_r5);
    _r6 = var_x;
    _r7 = var_y;
    _r8 = _r6 * _r7;
    bunzo_print_int(_r8);
    _r9 = var_y;
    _r10 = var_x;
    _r11 = _r9 / _r10;
    bunzo_print_int(_r11);
    return;
}

/* Entry Point wrapper */
int main(int argc, char** argv) {
    escape_main__main__();
    return 0;
}
