name: Release to SourceForge

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: bunzo-linux
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.linux_run_id }}
          path: release

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: bunzo-windows
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.windows_run_id }}
          path: release

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SF_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts

      - name: Upload All Files to SourceForge
        run: |
          scp \
            release/bunzo-linux-x86_64.tar.gz \
            release/bunzo-windows-x86_64.zip \
            scripts/install.sh \
            scripts/install.ps1 \
            ${{ secrets.SF_USERNAME }}@frs.sourceforge.net:/home/frs/project/bunzo/